variables:
  CI_REGISTRY_URL: "YOUR_JFROG_DOCKER_REGISTRY_URL"
  JFROG_URL: "YOUR_JFROG_PLATFORM_BASE_URL"
  JFROG_USERNAME: "$JFROG_USERNAME"
  JFROG_PASSWORD: "$JFROG_PASSWORD"

  CI_IMAGE_NAME: "$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA"

stages:
  - build_and_push
  - scan

build_and_push_image:
  stage: build_and_push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Starting Docker Build and Push to Artifactory..."

    - echo "$JFROG_PASSWORD" | docker login "$CI_REGISTRY_URL" -u "$JFROG_USERNAME" --password-stdin

    - docker build --pull -t "$CI_REGISTRY_URL/$CI_IMAGE_NAME" .

    - docker push "$CI_REGISTRY_URL/$CI_IMAGE_NAME"

    - echo "Successfully built and pushed image: $CI_REGISTRY_URL/$CI_IMAGE_NAME"

jfrog_security_scan:
  stage: scan
  image: jfrog/jfrog-cli:latest
  needs: ["build_and_push_image"]
  when: on_success
  script:
    - echo "Starting JFrog Xray Scan..."

    - jfrog rt c artifactory-server --url="$JFROG_URL" --user="$JFROG_USERNAME" --password="$JFROG_PASSWORD" --interactive=false

    - REPO_NAME=$(echo "$CI_REGISTRY_URL" | sed 's/.*\///')

    - jfrog rt scan "$REPO_NAME/$CI_IMAGE_NAME" --fail-build=true

    - echo "JFrog Xray scan completed."
